final List<Map<String, dynamic>> shoes = [
  // ====================== NIKE (id: 1) ======================
  {
    "id": 1,
    "name": "Nike Air Max 1",
    "brands": 1,
    "price": 3500000,
    "image": "https://picsum.photos/id/1/400/400",
    "descriptions": "Mẫu giày Nike Air Max kinh điển.",
  },
  {
    "id": 2,
    "name": "Nike Air Max 90",
    "brands": 1,
    "price": 4200000,
    "image": "https://picsum.photos/id/2/400/400",
    "descriptions": "Thiết kế mạnh mẽ và êm ái.",
  },
  {
    "id": 3,
    "name": "Nike Jordan Retro 1",
    "brands": 1,
    "price": 5800000,
    "image": "https://picsum.photos/id/3/400/400",
    "descriptions": "Huyền thoại Jordan Retro 1.",
  },
  {
    "id": 4,
    "name": "Nike Jordan Retro 4",
    "brands": 1,
    "price": 6200000,
    "image": "https://picsum.photos/id/4/400/400",
    "descriptions": "Phong cách cổ điển, sang trọng.",
  },
  {
    "id": 5,
    "name": "Nike Zoom Fly",
    "brands": 1,
    "price": 3600000,
    "image": "https://picsum.photos/id/5/400/400",
    "descriptions": "Giày chạy bộ siêu nhẹ.",
  },
  {
    "id": 6,
    "name": "Nike Pegasus 40",
    "brands": 1,
    "price": 2950000,
    "image": "https://picsum.photos/id/6/400/400",
    "descriptions": "Đôi giày chạy tốt nhất của Nike.",
  },
  {
    "id": 7,
    "name": "Nike Air Force 1",
    "brands": 1,
    "price": 3200000,
    "image": "https://picsum.photos/id/7/400/400",
    "descriptions": "Phong cách thời trang đường phố.",
  },
  {
    "id": 8,
    "name": "Nike Dunk Low",
    "brands": 1,
    "price": 3990000,
    "image": "https://picsum.photos/id/8/400/400",
    "descriptions": "Mẫu sneaker cực hot năm nay.",
  },
  {
    "id": 9,
    "name": "Nike Dunk High",
    "brands": 1,
    "price": 4500000,
    "image": "https://picsum.photos/id/9/400/400",
    "descriptions": "Thiết kế cổ cao mạnh mẽ.",
  },
  {
    "id": 10,
    "name": "Nike Metcon 8",
    "brands": 1,
    "price": 3500000,
    "image": "https://picsum.photos/id/10/400/400",
    "descriptions": "Giày tập gym cực kỳ ổn định.",
  },
  {
    "id": 11,
    "name": "Nike React Vision",
    "brands": 1,
    "price": 3600000,
    "image": "https://picsum.photos/id/11/400/400",
    "descriptions": "Thoải mái, nhẹ và êm.",
  },
  {
    "id": 12,
    "name": "Nike Court Vision",
    "brands": 1,
    "price": 2800000,
    "image": "https://picsum.photos/id/12/400/400",
    "descriptions": "Giày thời trang phong cách basketball.",
  },
  {
    "id": 13,
    "name": "Nike Air Max 270",
    "brands": 1,
    "price": 4700000,
    "image": "https://picsum.photos/id/13/400/400",
    "descriptions": "Đế khí lớn, siêu êm.",
  },
  {
    "id": 14,
    "name": "Nike Revolution 6",
    "brands": 1,
    "price": 1950000,
    "image": "https://picsum.photos/id/14/400/400",
    "descriptions": "Giày chạy giá rẻ đáng mua.",
  },
  {
    "id": 15,
    "name": "Nike Infinity Run 3",
    "brands": 1,
    "price": 4500000,
    "image": "https://picsum.photos/id/15/400/400",
    "descriptions": "Hỗ trợ giảm chấn tuyệt vời.",
  },

  // ====================== PUMA (id: 2) ======================
  {
    "id": 16,
    "name": "Puma RS-X",
    "brands": 2,
    "price": 3200000,
    "image": "https://picsum.photos/id/16/400/400",
    "descriptions": "Thiết kế trẻ trung năng động.",
  },
  {
    "id": 17,
    "name": "Puma Suede Classic",
    "brands": 2,
    "price": 2500000,
    "image": "https://picsum.photos/id/17/400/400",
    "descriptions": "Mẫu suede huyền thoại.",
  },
  {
    "id": 18,
    "name": "Puma Rider",
    "brands": 2,
    "price": 2700000,
    "image": "https://picsum.photos/id/18/400/400",
    "descriptions": "Phong cách retro cá tính.",
  },
  {
    "id": 19,
    "name": "Puma Smash v2",
    "brands": 2,
    "price": 1800000,
    "image": "https://picsum.photos/id/19/400/400",
    "descriptions": "Giá rẻ nhưng rất bền.",
  },
  {
    "id": 20,
    "name": "Puma Axelion",
    "brands": 2,
    "price": 2200000,
    "image": "https://picsum.photos/id/20/400/400",
    "descriptions": "Thiết kế thể thao hiện đại.",
  },
  {
    "id": 21,
    "name": "Puma Cell Surin",
    "brands": 2,
    "price": 2600000,
    "image": "https://picsum.photos/id/21/400/400",
    "descriptions": "Đệm Cell êm ái.",
  },
  {
    "id": 22,
    "name": "Puma X-Ray",
    "brands": 2,
    "price": 2300000,
    "image": "https://picsum.photos/id/22/400/400",
    "descriptions": "Thiết kế trẻ trung.",
  },
  {
    "id": 23,
    "name": "Puma Tazon 6",
    "brands": 2,
    "price": 2100000,
    "image": "https://picsum.photos/id/23/400/400",
    "descriptions": "Giày tập cực ổn định.",
  },
  {
    "id": 24,
    "name": "Puma Ferrari Drift",
    "brands": 2,
    "price": 3500000,
    "image": "https://picsum.photos/id/24/400/400",
    "descriptions": "Logo Ferrari sang trọng.",
  },
  {
    "id": 25,
    "name": "Puma Graviton",
    "brands": 2,
    "price": 2400000,
    "image": "https://picsum.photos/id/25/400/400",
    "descriptions": "Phong cách hiện đại.",
  },
  {
    "id": 26,
    "name": "Puma Comet 2",
    "brands": 2,
    "price": 1600000,
    "image": "https://picsum.photos/id/26/400/400",
    "descriptions": "Giày chạy đơn giản.",
  },
  {
    "id": 27,
    "name": "Puma Electron 2",
    "brands": 2,
    "price": 2000000,
    "image": "https://picsum.photos/id/27/400/400",
    "descriptions": "Rất nhẹ và thoải mái.",
  },
  {
    "id": 28,
    "name": "Puma Court Classic",
    "brands": 2,
    "price": 1900000,
    "image": "https://picsum.photos/id/28/400/400",
    "descriptions": "Phong cách tennis cổ điển.",
  },
  {
    "id": 29,
    "name": "Puma RS-Fast",
    "brands": 2,
    "price": 3300000,
    "image": "https://picsum.photos/id/29/400/400",
    "descriptions": "Thiết kế chunky nổi bật.",
  },
  {
    "id": 30,
    "name": "Puma UltraRide",
    "brands": 2,
    "price": 2600000,
    "image": "https://picsum.photos/id/30/400/400",
    "descriptions": "Giày chạy bộ hiệu suất cao.",
  },

  // ====================== JORDAN (id: 3) ======================
  {
    "id": 31,
    "name": "Jordan 1 Mid",
    "brands": 3,
    "price": 4500000,
    "image": "https://picsum.photos/id/31/400/400",
    "descriptions": "Mẫu Jordan phổ biến nhất.",
  },
  {
    "id": 32,
    "name": "Jordan 1 Low",
    "brands": 3,
    "price": 3900000,
    "image": "https://picsum.photos/id/32/400/400",
    "descriptions": "Phong cách trẻ trung.",
  },
  {
    "id": 33,
    "name": "Jordan 4 Retro",
    "brands": 3,
    "price": 6500000,
    "image": "https://picsum.photos/id/33/400/400",
    "descriptions": "Cực hot trong cộng đồng sneaker.",
  },
  {
    "id": 34,
    "name": "Jordan 11 Low",
    "brands": 3,
    "price": 7200000,
    "image": "https://picsum.photos/id/34/400/400",
    "descriptions": "Thiết kế bóng bẩy sang trọng.",
  },
  {
    "id": 35,
    "name": "Jordan 6 Retro",
    "brands": 3,
    "price": 6900000,
    "image": "https://picsum.photos/id/35/400/400",
    "descriptions": "Một trong các đôi retro đẹp nhất.",
  },
  {
    "id": 36,
    "name": "Jordan 3 Retro",
    "brands": 3,
    "price": 6300000,
    "image": "https://picsum.photos/id/36/400/400",
    "descriptions": "Phối màu Elephant print đặc trưng.",
  },
  {
    "id": 37,
    "name": "Jordan 5 Retro",
    "brands": 3,
    "price": 6200000,
    "image": "https://picsum.photos/id/37/400/400",
    "descriptions": "Phong cách chiến binh mạnh mẽ.",
  },
  {
    "id": 38,
    "name": "Jordan Max Aura",
    "brands": 3,
    "price": 3900000,
    "image": "https://picsum.photos/id/38/400/400",
    "descriptions": "Thiết kế cổ điển nhưng hiện đại.",
  },
  {
    "id": 39,
    "name": "Jordan Stay Loyal",
    "brands": 3,
    "price": 3500000,
    "image": "https://picsum.photos/id/39/400/400",
    "descriptions": "Thoải mái khi vận động.",
  },
  {
    "id": 40,
    "name": "Jordan Lift Off",
    "brands": 3,
    "price": 3200000,
    "image": "https://picsum.photos/id/40/400/400",
    "descriptions": "Nổi bật trên sân bóng rổ.",
  },
  {
    "id": 41,
    "name": "Jordan Access",
    "brands": 3,
    "price": 3000000,
    "image": "https://picsum.photos/id/41/400/400",
    "descriptions": "Kiểu dáng đơn giản.",
  },
  {
    "id": 42,
    "name": "Jordan Jumpman 2021",
    "brands": 3,
    "price": 4300000,
    "image": "https://picsum.photos/id/42/400/400",
    "descriptions": "Dành cho người chơi bóng rổ nghiệp dư.",
  },
  {
    "id": 43,
    "name": "Jordan Luka 1",
    "brands": 3,
    "price": 3900000,
    "image": "https://picsum.photos/id/43/400/400",
    "descriptions": "Mẫu signature của Luka Dončić.",
  },
  {
    "id": 44,
    "name": "Jordan Zion 2",
    "brands": 3,
    "price": 4200000,
    "image": "https://picsum.photos/id/44/400/400",
    "descriptions": "Đệm tốt và bám sân tốt.",
  },
  {
    "id": 45,
    "name": "Jordan Westbrook One Take",
    "brands": 3,
    "price": 3500000,
    "image": "https://picsum.photos/id/45/400/400",
    "descriptions": "Cực nhẹ và nhanh nhẹn.",
  },

  // ====================== ADIDAS (id: 4) ======================
  {
    "id": 46,
    "name": "Adidas Ultraboost 22",
    "brands": 4,
    "price": 5000000,
    "image": "https://picsum.photos/id/46/400/400",
    "descriptions": "Boost êm nhất của Adidas.",
  },
  {
    "id": 47,
    "name": "Adidas Superstar",
    "brands": 4,
    "price": 2600000,
    "image": "https://picsum.photos/id/47/400/400",
    "descriptions": "Mẫu giày vỏ sò huyền thoại.",
  },
  {
    "id": 48,
    "name": "Adidas Stan Smith",
    "brands": 4,
    "price": 2500000,
    "image": "https://picsum.photos/id/48/400/400",
    "descriptions": "Phong cách tối giản sang trọng.",
  },
  {
    "id": 49,
    "name": "Adidas NMD R1",
    "brands": 4,
    "price": 3800000,
    "image": "https://picsum.photos/id/49/400/400",
    "descriptions": "Cực êm và hợp thời trang.",
  },
  {
    "id": 50,
    "name": "Adidas Yeezy 350",
    "brands": 4,
    "price": 6900000,
    "image": "https://picsum.photos/id/50/400/400",
    "descriptions": "Chunky style độc đáo.",
  },
  {
    "id": 51,
    "name": "Adidas Forum Low",
    "brands": 4,
    "price": 2900000,
    "image": "https://picsum.photos/id/51/400/400",
    "descriptions": "Retro đầy cá tính.",
  },
  {
    "id": 52,
    "name": "Adidas Alphabounce",
    "brands": 4,
    "price": 2100000,
    "image": "https://picsum.photos/id/52/400/400",
    "descriptions": "Êm ái cho chạy bộ.",
  },
  {
    "id": 53,
    "name": "Adidas Solar Glide",
    "brands": 4,
    "price": 3400000,
    "image": "https://picsum.photos/id/53/400/400",
    "descriptions": "Giày chạy hiệu suất cao.",
  },
  {
    "id": 54,
    "name": "Adidas 4D FWD",
    "brands": 4,
    "price": 4800000,
    "image": "https://picsum.photos/id/54/400/400",
    "descriptions": "Đế 4D tương lai.",
  },
  {
    "id": 55,
    "name": "Adidas Ozelia",
    "brands": 4,
    "price": 2700000,
    "image": "https://picsum.photos/id/55/400/400",
    "descriptions": "Thiết kế đậm chất retro.",
  },
  {
    "id": 56,
    "name": "Adidas Campus 00s",
    "brands": 4,
    "price": 3000000,
    "image": "https://picsum.photos/id/56/400/400",
    "descriptions": "Phong cách skate cổ điển.",
  },
  {
    "id": 57,
    "name": "Adidas RunFalcon",
    "brands": 4,
    "price": 1400000,
    "image": "https://picsum.photos/id/57/400/400",
    "descriptions": "Giá rẻ cực đáng mua.",
  },
  {
    "id": 58,
    "name": "Adidas Lite Racer",
    "brands": 4,
    "price": 1600000,
    "image": "https://picsum.photos/id/58/400/400",
    "descriptions": "Dành cho người thích sự nhẹ nhàng.",
  },
  {
    "id": 59,
    "name": "Adidas Duramo SL",
    "brands": 4,
    "price": 1800000,
    "image": "https://picsum.photos/id/59/400/400",
    "descriptions": "Thoáng khí và linh hoạt.",
  },
  {
    "id": 60,
    "name": "Adidas CourtJam Bounce",
    "brands": 4,
    "price": 2200000,
    "image": "https://picsum.photos/id/60/400/400",
    "descriptions": "Dành cho chơi tennis.",
  },

  // ====================== CONVERSE (id: 5) ======================
  {
    "id": 61,
    "name": "Converse Chuck 70",
    "brands": 5,
    "price": 2100000,
    "image": "https://picsum.photos/id/61/400/400",
    "descriptions": "Mẫu giày canvas huyền thoại.",
  },
  {
    "id": 62,
    "name": "Converse Classic High",
    "brands": 5,
    "price": 1500000,
    "image": "https://picsum.photos/id/62/400/400",
    "descriptions": "Phong cách trường tồn với thời gian.",
  },
  {
    "id": 63,
    "name": "Converse Classic Low",
    "brands": 5,
    "price": 1400000,
    "image": "https://picsum.photos/id/63/400/400",
    "descriptions": "Đơn giản nhưng đẹp.",
  },
  {
    "id": 64,
    "name": "Converse Run Star Hike",
    "brands": 5,
    "price": 2600000,
    "image": "https://picsum.photos/id/64/400/400",
    "descriptions": "Đế giày cao độc đáo.",
  },
  {
    "id": 65,
    "name": "Converse Move Platform",
    "brands": 5,
    "price": 2300000,
    "image": "https://picsum.photos/id/65/400/400",
    "descriptions": "Tôn dáng, tăng chiều cao.",
  },
  {
    "id": 66,
    "name": "Converse Pro Leather",
    "brands": 5,
    "price": 2500000,
    "image": "https://picsum.photos/id/66/400/400",
    "descriptions": "Phong cách bóng rổ retro.",
  },
  {
    "id": 67,
    "name": "Converse One Star",
    "brands": 5,
    "price": 2200000,
    "image": "https://picsum.photos/id/67/400/400",
    "descriptions": "Biểu tượng một ngôi sao.",
  },
  {
    "id": 68,
    "name": "Converse All Star CX",
    "brands": 5,
    "price": 2000000,
    "image": "https://picsum.photos/id/68/400/400",
    "descriptions": "Cải tiến với công nghệ CX.",
  },
  {
    "id": 69,
    "name": "Converse Weapon",
    "brands": 5,
    "price": 2900000,
    "image": "https://picsum.photos/id/69/400/400",
    "descriptions": "Gắn với NBA thập niên 80.",
  },
  {
    "id": 70,
    "name": "Converse Star Player",
    "brands": 5,
    "price": 1600000,
    "image": "https://picsum.photos/id/70/400/400",
    "descriptions": "Phong cách thể thao cổ điển.",
  },
  {
    "id": 71,
    "name": "Converse Lugged 2.0",
    "brands": 5,
    "price": 2600000,
    "image": "https://picsum.photos/id/71/400/400",
    "descriptions": "Đế giày cao su chống trượt.",
  },
  {
    "id": 72,
    "name": "Converse Skid Grip",
    "brands": 5,
    "price": 1700000,
    "image": "https://picsum.photos/id/72/400/400",
    "descriptions": "Phong cách vintage.",
  },
  {
    "id": 73,
    "name": "Converse CTAS Lift",
    "brands": 5,
    "price": 1900000,
    "image": "https://picsum.photos/id/73/400/400",
    "descriptions": "Platform nhẹ và đẹp.",
  },
  {
    "id": 74,
    "name": "Converse All Terrain",
    "brands": 5,
    "price": 2400000,
    "image": "https://picsum.photos/id/74/400/400",
    "descriptions": "Đi được nhiều loại địa hình.",
  },
  {
    "id": 75,
    "name": "Converse Trail Mission",
    "brands": 5,
    "price": 2200000,
    "image": "https://picsum.photos/id/75/400/400",
    "descriptions": "Thiết kế bụi bặm, cá tính.",
  },
];

List<Map<String, dynamic>> brandsData = [
  {
    "id": 1,
    "name": "Nike",
    "image":
        "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Logo_NIKE.svg/100px-Logo_NIKE.svg.png",
  },
  {
    "id": 2,
    "name": "Puma",
    "image":
        "https://rubee.com.vn/admin/webroot/upload/image//images/tin-tuc/puma-logo-3.jpg",
  },
  {
    "id": 3,
    "name": "Jordan",
    "image":
        "https://jordan1.vn/wp-content/uploads/2023/09/under-armour-logo-700x394_da9de84943ae4c90a693b34480ef20df_1024x1024.png",
  },
  {
    "id": 4,
    "name": "Adidas",
    "image":
        "https://inkythuatso.com/uploads/thumbnails/800/2021/09/logo-adidas-vector-inkythuatso-01-29-09-08-58.jpg",
  },
  {
    "id": 5,
    "name": "Converse",
    "image":
        "https://drake.vn/image/catalog/H%C3%ACnh%20content/logo%20gi%C3%A0y%20Converse/logo-gi%C3%A0y-converse-02.jpg",
  },
];
